"""Renders the same REST call list already used for iControl REST as an
Ansible playbook (ansible.builtin.uri tasks) -- for the common real-world
case where a migration gets executed through an Ansible controller rather
than a REST client or tmsh session by hand. This is a faithful, mechanical
re-expression of generate_rest()/generate_full_recreate_rest()'s output,
not a second parallel translation of the migration plan -- it can never
disagree with the REST tab about what actually changes, because it loops
over the exact same RestCall list.

JSON is valid YAML flow-mapping syntax, so each call's body is emitted with
json.dumps() rather than a hand-rolled YAML serializer -- this guarantees
every body round-trips correctly regardless of nesting, without pulling in
a yaml dependency the rest of the backend doesn't otherwise need.
"""
import json
from typing import List

from app.generation.rest_generator import RestCall

_PLAYBOOK_HEADER = """---
- name: F5 BIG-IP migration -- generated by Config Intelligence
  hosts: f5_target
  gather_facts: false
  vars:
    f5_host: "{{ f5_host }}"
    f5_user: "{{ f5_user }}"
    f5_password: "{{ f5_password }}"
  tasks:"""

_NO_CALLS_PLAYBOOK = """---
- name: F5 BIG-IP migration -- generated by Config Intelligence
  hosts: f5_target
  gather_facts: false
  tasks:
    - name: No changes to apply
      ansible.builtin.debug:
        msg: "This migration plan produced no REST calls -- nothing to run."
"""

_TASK_TEMPLATE = """
    - name: "Step {step}: {method} {path}"
      ansible.builtin.uri:
        url: "https://{{{{ f5_host }}}}{path}"
        method: {method}
        user: "{{{{ f5_user }}}}"
        password: "{{{{ f5_password }}}}"
        force_basic_auth: true
        validate_certs: false
        body_format: json
        body: {body_json}
        status_code: [200, 201, 202]"""


def generate_ansible_playbook(rest_calls: List[RestCall]) -> str:
    if not rest_calls:
        return _NO_CALLS_PLAYBOOK

    parts = [_PLAYBOOK_HEADER]
    for step, call in enumerate(rest_calls, start=1):
        parts.append(
            _TASK_TEMPLATE.format(
                step=step,
                method=call.method,
                path=call.path,
                body_json=json.dumps(call.body),
            )
        )
    return "\n".join(parts) + "\n"
